import profpanel

class CharacterSkill():
    def __init__(self):
        self.acrobatics = profpanel.ProfPanel(300, 180, "acrobatics")
        self.animalHandling = profpanel.ProfPanel(300, 205, "animal handling")
        self.arcana = profpanel.ProfPanel(300, 230, "arcana")
        self.athletics = profpanel.ProfPanel(300, 255, "athletics")
        self.deception = profpanel.ProfPanel(300, 280, "deception")
        self.history = profpanel.ProfPanel(300, 305, "history")
        self.insight = profpanel.ProfPanel(300, 330, "insight")
        self.intimidation = profpanel.ProfPanel(300, 355, "intimidation")
        self.investigation = profpanel.ProfPanel(300, 380, "investigation")
        self.medicine = profpanel.ProfPanel(300, 405, "medicine")
        self.nature = profpanel.ProfPanel(300, 430, "nature")
        self.perception = profpanel.ProfPanel(300, 455, "perception")
        self.performance = profpanel.ProfPanel(300, 480, "performance")
        self.persuasion = profpanel.ProfPanel(300, 505, "persuasion")
        self.religion = profpanel.ProfPanel(300, 530, "religion")
        self.slightOfHand = profpanel.ProfPanel(300, 555, "slight of hand")
        self.stealth = profpanel.ProfPanel(300, 580, "stealth")
        self.survival = profpanel.ProfPanel(300, 605, "survival")

    def draw(self, surface):
        self.acrobatics.draw(surface)
        self.animalHandling.draw(surface)
        self.arcana.draw(surface)
        self.athletics.draw(surface)
        self.deception.draw(surface)
        self.history.draw(surface)
        self.insight.draw(surface)
        self.intimidation.draw(surface)
        self.investigation.draw(surface)
        self.medicine.draw(surface)
        self.nature.draw(surface)
        self.perception.draw(surface)
        self.performance.draw(surface)
        self.persuasion.draw(surface)
        self.religion.draw(surface)
        self.slightOfHand.draw(surface)
        self.stealth.draw(surface)
        self.survival.draw(surface)

    def update(self, events):
        self.acrobatics.update(events)
        self.animalHandling.update(events)
        self.arcana.update(events)
        self.athletics.update(events)
        self.deception.update(events)
        self.history.update(events)
        self.insight.update(events)
        self.intimidation.update(events)
        self.investigation.update(events)
        self.medicine.update(events)
        self.nature.update(events)
        self.perception.update(events)
        self.performance.update(events)
        self.persuasion.update(events)
        self.religion.update(events)
        self.slightOfHand.update(events)
        self.stealth.update(events)
        self.survival.update(events)

    def save(self):
        self.acrobatics.save()
        self.animalHandling.save()
        self.arcana.save()
        self.athletics.save()
        self.deception.save()
        self.history.save()
        self.insight.save()
        self.intimidation.save()
        self.investigation.save()
        self.medicine.save()
        self.nature.save()
        self.perception.save()
        self.performance.save()
        self.persuasion.save()
        self.religion.save()
        self.slightOfHand.save()
        self.stealth.save()
        self.survival.save()

    def load(self):
        self.acrobatics.load()
        self.animalHandling.load()
        self.arcana.load()
        self.athletics.load()
        self.deception.load()
        self.history.load()
        self.insight.load()
        self.intimidation.load()
        self.investigation.load()
        self.medicine.load()
        self.nature.load()
        self.perception.load()
        self.performance.load()
        self.persuasion.load()
        self.religion.load()
        self.slightOfHand.load()
        self.stealth.load()
        self.survival.load()