import profpanel

class CharacterSkill():
    def __init__(self):
        self.acrobatics = profpanel.ProfPanel(200, 300, "acrobatics")
        self.animalHandling = profpanel.ProfPanel(200, 325, "animal handling")
        self.arcana = profpanel.ProfPanel(200, 350, "arcana")
        self.athletics = profpanel.ProfPanel(200, 375, "athletics")
        self.deception = profpanel.ProfPanel(200, 400, "deception")
        self.history = profpanel.ProfPanel(200, 425, "history")
        self.insight = profpanel.ProfPanel(200, 450, "insight")
        self.intimidation = profpanel.ProfPanel(200, 475, "intimidation")
        self.investigation = profpanel.ProfPanel(200, 500, "investigation")
        self.medicine = profpanel.ProfPanel(200, 525, "medicine")
        self.nature = profpanel.ProfPanel(200, 550, "nature")
        self.perception = profpanel.ProfPanel(200, 575, "perception")
        self.performance = profpanel.ProfPanel(200, 600, "performance")
        self.persuasion = profpanel.ProfPanel(200, 625, "persuasion")
        self.religion = profpanel.ProfPanel(200, 650, "religion")
        self.slightOfHand = profpanel.ProfPanel(200, 675, "slight of hand")
        self.stealth = profpanel.ProfPanel(200, 700, "stealth")
        self.survival = profpanel.ProfPanel(200, 725, "survival")

    def draw(self, surface):
        self.acrobatics.draw(surface)
        self.animalHandling.draw(surface)
        self.arcana.draw(surface)
        self.athletics.draw(surface)
        self.deception.draw(surface)
        self.history.draw(surface)
        self.insight.draw(surface)
        self.intimidation.draw(surface)
        self.investigation.draw(surface)
        self.medicine.draw(surface)
        self.nature.draw(surface)
        self.perception.draw(surface)
        self.performance.draw(surface)
        self.persuasion.draw(surface)
        self.religion.draw(surface)
        self.slightOfHand.draw(surface)
        self.stealth.draw(surface)
        self.survival.draw(surface)

    def update(self, events):
        self.acrobatics.update(events)
        self.animalHandling.update(events)
        self.arcana.update(events)
        self.athletics.update(events)
        self.deception.update(events)
        self.history.update(events)
        self.insight.update(events)
        self.intimidation.update(events)
        self.investigation.update(events)
        self.medicine.update(events)
        self.nature.update(events)
        self.perception.update(events)
        self.performance.update(events)
        self.persuasion.update(events)
        self.religion.update(events)
        self.slightOfHand.update(events)
        self.stealth.update(events)
        self.survival.update(events)

    def save(self):
        self.acrobatics.save()
        self.animalHandling.save()
        self.arcana.save()
        self.athletics.save()
        self.deception.save()
        self.history.save()
        self.insight.save()
        self.intimidation.save()
        self.investigation.save()
        self.medicine.save()
        self.nature.save()
        self.perception.save()
        self.performance.save()
        self.persuasion.save()
        self.religion.save()
        self.slightOfHand.save()
        self.stealth.save()
        self.survival.save()

    def load(self):
        self.acrobatics.load()
        self.animalHandling.load()
        self.arcana.load()
        self.athletics.load()
        self.deception.load()
        self.history.load()
        self.insight.load()
        self.intimidation.load()
        self.investigation.load()
        self.medicine.load()
        self.nature.load()
        self.perception.load()
        self.performance.load()
        self.persuasion.load()
        self.religion.load()
        self.slightOfHand.load()
        self.stealth.load()
        self.survival.load()